const logger = require('./logger');

function markdownToHtml(markdown, title) {
  let body = markdown
    .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
    .replace(/^### (.+)$/gm,  '<h3>$1</h3>')
    .replace(/^## (.+)$/gm,   '<h2>$1</h2>')
    .replace(/^# (.+)$/gm,    '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em>$1</em>')
    .replace(/`([^`]+)`/g,    '<code>$1</code>')
    .replace(/```[\w]*\n([\s\S]*?)```/g, '<pre><code>$1</code></pre>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/^---$/gm, '<hr>')
    .replace(/(<li>.*<\/li>\n?)+/g, match => `<ul>${match}</ul>`)
    .replace(/^(?!<[hlbpuoir]|<\/|<code|<pre|<hr)(.+)$/gm, '<p>$1</p>');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>SRS — ${title}</title>
<style>
  body { font-family: Georgia, serif; font-size: 11pt; line-height: 1.75; color: #1a1a2e; padding: 40px 60px; max-width: 900px; margin: 0 auto; }
  h1 { font-size: 22pt; color: #0f3460; border-bottom: 2px solid #0f3460; padding-bottom: 6px; margin: 32px 0 10px; }
  h2 { font-size: 16pt; color: #1a1a2e; border-left: 4px solid #6c63ff; padding-left: 8px; margin: 24px 0 8px; }
  h3 { font-size: 13pt; margin: 16px 0 6px; }
  h4 { font-size: 11pt; font-style: italic; margin: 10px 0 4px; }
  p  { margin: 6px 0; }
  hr { border: none; border-top: 1px solid #ddd; margin: 20px 0; }
  ul { margin: 8px 0 8px 24px; }
  li { margin: 3px 0; }
  code { background: #f4f4f4; padding: 1px 5px; border-radius: 3px; font-size: 9.5pt; font-family: monospace; }
  pre  { background: #1e1e2e; color: #e2e2f0; padding: 12px 16px; border-radius: 6px; margin: 10px 0; }
  pre code { background: none; color: inherit; padding: 0; }
  .cover { text-align: center; padding: 60px 40px; background: #0f0f1a; color: #e2e2f0; page-break-after: always; }
  .cover h1 { color: #fff; border: none; font-size: 28pt; }
  .cover p  { color: #8888a4; }
  @page { margin: 20mm 15mm; }
</style></head><body>
<div class="cover">
  <p>Software Requirements Specification</p>
  <h1>${title}</h1>
  <p>Generated by DevSpectra AI — ${new Date().toLocaleDateString()}</p>
  <p style="color:#6c63ff;">IEEE 830 Compliant</p>
</div>
<div class="content">${body}</div>
</body></html>`;
}

async function generatePdf(srsMarkdown, projectTitle) {
  let browser;
  try {
    const puppeteer = require('puppeteer');
    browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    const page = await browser.newPage();
    const html = markdownToHtml(srsMarkdown, projectTitle);
    await page.setContent(html, { waitUntil: 'domcontentloaded' });
    await page.evaluate(() => document.fonts.ready);
    const pdf = await page.pdf({
      format: 'A4', printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
    });
    return pdf;
  } catch (err) {
    logger.error('PDF generation error:', err);
    throw err;
  } finally {
    if (browser) await browser.close();
  }
}

module.exports = { generatePDF: generatePdf, markdownToHtml };